apiVersion: surfboard.ado/v1
kind: WorkItemDefaults
metadata:
  name: workspace-defaults
spec:
  global:
    fields:
      System.AreaPath: Alliant\Shared Services\Site Reliability Engineering
      System.IterationPath: Alliant\SRE\26Q3
      System.Description: |-
        This is the default description for all work items.
      Microsoft.VSTS.Common.AcceptanceCriteria: |-
        - Bullet 1
        - Bullet 2
      Microsoft.VSTS.Common.ValueArea: Architectural
      Custom.Product: Platform
  kinds:
    Feature:
      fields:
        Custom.BenefitHypothesis: Make things faster, better, stronger

    # PBI:
    #   fields:
    #     System.State: New
