apiVersion: surfboard.ado/v1
kind: Feature
metadata:
  localId: feature-221835
  adoId: 221835
spec:
  fields:
    System.State: New
    System.Reason: New feature
    System.Title: witt test feature
    Microsoft.VSTS.Common.Priority: 4
    Microsoft.VSTS.Common.BacklogPriority: 1652650240
    Microsoft.VSTS.Common.StateChangeDate: 2026-05-07T05:56:06.213Z
    WEF_754C0B46226E498E9FB3B66CF0B527A9_Kanban.Column: New
    WEF_754C0B46226E498E9FB3B66CF0B527A9_Kanban.Column.Done: false
    WEF_6FC02DE26073442396CD4E65C003C170_Kanban.Column: New
    WEF_6FC02DE26073442396CD4E65C003C170_Kanban.Column.Done: false
    Custom.WSJF: 0
    System.Description: <div>Witt will delete by September 2026. </div>
    Custom.BenefitHypothesis: get-this-field
---
apiVersion: surfboard.ado/v1
kind: PBI
metadata:
  localId: pbi-bb5d68b0
  adoId: 223293
spec:
  parent:
    adoId: 221835
    localId: feature-221835
  fields:
    System.State: New
    System.Reason: New backlog item
    System.Title: child 1
    Microsoft.VSTS.Common.Priority: 4
    Microsoft.VSTS.Common.StateChangeDate: 2026-05-19T03:32:59.003Z
    WEF_70E7AA846FE843908BE008120B3355F7_Kanban.Column: New
    WEF_70E7AA846FE843908BE008120B3355F7_Kanban.Column.Done: false
    System.Description: |-
      a
      line
      separated
      description
    Microsoft.VSTS.Common.AcceptanceCriteria: |-
      - Bullet 1
      - Bullet 2 formerly in RTF
---
apiVersion: surfboard.ado/v1
kind: PBI
metadata:
  localId: pbi-647d49f8
  adoId: 223294
spec:
  parent:
    adoId: 221835
    localId: feature-221835
  fields:
    System.State: New
    System.Reason: New backlog item
    System.Title: child 2
    Microsoft.VSTS.Common.Priority: 4
    Microsoft.VSTS.Common.StateChangeDate: 2026-05-19T03:36:08.27Z
    Microsoft.VSTS.Common.ValueArea: Business
    WEF_70E7AA846FE843908BE008120B3355F7_Kanban.Column: New
    WEF_70E7AA846FE843908BE008120B3355F7_Kanban.Column.Done: false
    Custom.Product: Other
    System.Description: |-
      markdown
      line
      separated
      _description_
    Microsoft.VSTS.Common.AcceptanceCriteria: |-
      - Bullet 1 in md
      - Bullet 2 in MD
